fwqfwqf

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -26,8 +26,12 @@ jobs:
       - name: Run stress test
         run: wget -O stress_test.js https://raw.githubusercontent.com/MarcHedeby/k6WtfWorkPipelineBullshit/master/bygspy%20k6%20test/stress_test.js && k6 run stress_test.js
 
-      # Add a step to check if any previous steps have failed
-      - name: Check if any tests failed
+      # Add a step to check if any tests failed
+      - name: Check test results
+        run: exit $(($(find . -name "k6-results.json" -exec grep -c '"checks":\[\{.*"pass":false' {} +)))
+        if: always()
+
+      # Add a step to stop the workflow if any tests failed
+      - name: Stop workflow on failure
         if: failure()
-        run: exit 1  # This will cause the job to fail, preventing further steps and stopping the push
-        
+        run: exit 1
